/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tambo_mysql;

import Modelos.Productos;
import SQL.Conexion;
import Modelos.Categorias;
import Modelos.Codigos;
import Modelos.MetodoPago;
import Modelos.Ventas;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabri
 */

public class MenuPrincipal extends javax.swing.JFrame {

    
    Color defaultcolor, clickedcolor, white, black, purple;
    private String Email;
    double precio=0;
    int cantidad=0;
    double importe=0;
//    DefaultTableModel modelo=new DefaultTableModel();
//    modelo.addColumn();
    
    ArrayList<Productos> ListaVentas=new ArrayList<Productos>(); //Guardamos los atributos para la Tabla Carrito
    

    
    
    
    public MenuPrincipal() {
        initComponents();
        
        Categorias ct=new Categorias();
        DefaultComboBoxModel modeloProduct=new DefaultComboBoxModel(ct.mostrarcategorias());
        jcbxCategoria.setModel(modeloProduct);
        
        defaultcolor=new Color(255, 204, 0);
        clickedcolor=new Color(104,17,130);
        white=new Color(255,255,255);
        black=new Color(0,0,0);
        purple=new Color(104,17,130);
        jtblTablaCarrito.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int filaSeleccionada = jtblTablaCarrito.getSelectedRow();
                    int columnaSeleccionada = jtblTablaCarrito.getSelectedColumn();
                    if (filaSeleccionada != -1 && columnaSeleccionada != -1) {
                        Object valorCelda = jtblTablaCarrito.getValueAt(filaSeleccionada, columnaSeleccionada);
                        jspNewCantidad.setValue(valorCelda);
                    }
                }
            }    
        });
        
//        SpinnerNumberModel spinnerModel = new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1);
//        jspNewCantidad.setModel(spinnerModel);
        
//        jspNewCantidad.addChangeListener(new ChangeListener() {
//            
//            @Override
//            public void stateChanged(ChangeEvent e) {
//                int filaSeleccionada = jtblTablaCarrito.getSelectedRow();
//                int columnaCantidad = 3;
//                if (filaSeleccionada != -1) {
//                    Object nuevoValor = jspNewCantidad.getValue();
//                    int cantidad1= (int) jtblTablaCarrito.getValueAt(filaSeleccionada, 3);
//                    double precio1= (double)jtblTablaCarrito.getValueAt(filaSeleccionada, 2);
//                    double importe1=Math.round(precio1*(cantidad1));
//                    
//                    
//                    jtblTablaCarrito.setValueAt(nuevoValor, filaSeleccionada, columnaCantidad);
//                    
//                    jtblTablaCarrito.setValueAt(importe1,filaSeleccionada, 4 );
//                }
//
//            }
//        });
//        
        
    }
    
    public String getEmail() {
        return Email;
}
    
   public void setEmail(String Email) {
       this.Email = Email;
        System.out.println(""+Email);
    }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        m1 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        m2 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        m3 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        m4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Comprar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProductos = new javax.swing.JTable();
        jcbxCategoria = new javax.swing.JComboBox<>();
        jcbxCodigos = new javax.swing.JComboBox<>();
        jspCantidad = new javax.swing.JSpinner();
        jbtnAgregarCarrito = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jblPrecio = new javax.swing.JLabel();
        jblImporte = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlbProducto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Carrito = new javax.swing.JPanel();
        jbtnPagar = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        jtblTablaCarrito = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jlbSubtotal = new javax.swing.JLabel();
        jlbIgv = new javax.swing.JLabel();
        jlbTotal = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jspNewCantidad = new javax.swing.JSpinner();
        Pagar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtApellidos = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtxtNombre = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtxtDireccion = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtxtDNI_Cliente = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtxtEmail = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtxtCelular = new javax.swing.JTextPane();
        jbtnCompletar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jtxtNumTarjeta = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jtxtFechaVencimiento = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jtxtCCV = new javax.swing.JTextPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jlbResumenSubtotal = new javax.swing.JLabel();
        jlbResumenIGV = new javax.swing.JLabel();
        jlbResumenTotal = new javax.swing.JLabel();
        jbtnProcesar = new javax.swing.JButton();
        Historial = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblHistorial = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlbDNI_Historial = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbDNIHis = new javax.swing.JLabel();

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMACIÓN DE VENTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("SUBTOTAL");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("IGV");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("TOTAL");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TAMBO");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(104, 17, 130));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setBackground(new java.awt.Color(255, 239, 0));

        m1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        m1.setForeground(new java.awt.Color(104, 17, 130));
        m1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m1.setText("COMPRAR");
        m1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                m1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                m1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 180, -1));

        p2.setBackground(new java.awt.Color(255, 239, 0));

        m2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        m2.setForeground(new java.awt.Color(104, 17, 130));
        m2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m2.setText("CARRITO");
        m2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                m2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                m2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 180, -1));

        p3.setBackground(new java.awt.Color(255, 239, 0));

        m3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        m3.setForeground(new java.awt.Color(104, 17, 130));
        m3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m3.setText("PAGAR");
        m3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                m3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                m3MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 180, -1));

        p4.setBackground(new java.awt.Color(255, 239, 0));

        m4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        m4.setForeground(new java.awt.Color(104, 17, 130));
        m4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m4.setText("HISTORIAL");
        m4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                m4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                m4MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 239, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(104, 17, 130));
        jButton2.setText("CERRAR SESIÓN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabri\\Downloads\\tambo-seeklogo.com(2).png")); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 560));

        jPanel3.setBackground(new java.awt.Color(104, 17, 130));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 961, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Comprar.setBackground(new java.awt.Color(255, 255, 255));

        jtblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Producto", "Descripción", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblProductos);
        if (jtblProductos.getColumnModel().getColumnCount() > 0) {
            jtblProductos.getColumnModel().getColumn(0).setResizable(false);
            jtblProductos.getColumnModel().getColumn(1).setResizable(false);
            jtblProductos.getColumnModel().getColumn(2).setResizable(false);
            jtblProductos.getColumnModel().getColumn(3).setResizable(false);
        }

        jcbxCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CATEGORÍA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jcbxCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbxCategoriaItemStateChanged(evt);
            }
        });
        jcbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxCategoriaActionPerformed(evt);
            }
        });

        jcbxCodigos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CÓDIGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jcbxCodigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxCodigosActionPerformed(evt);
            }
        });

        jspCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jspCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CANTIDAD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jspCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspCantidadStateChanged(evt);
            }
        });

        jbtnAgregarCarrito.setBackground(new java.awt.Color(104, 17, 130));
        jbtnAgregarCarrito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnAgregarCarrito.setForeground(new java.awt.Color(255, 239, 0));
        jbtnAgregarCarrito.setText("AGREGAR AL CARRITO");
        jbtnAgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarCarritoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("SELECCIONE LOS PRODUCTOS QUE DESEA!");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMACIÓN DE PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("IMPORTE");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("PRECIO");

        jblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jblImporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("PRODUCTO");

        jlbProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jblImporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );

        jButton1.setBackground(new java.awt.Color(104, 17, 130));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 239, 0));
        jButton1.setText("VER MI CARRITO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ComprarLayout = new javax.swing.GroupLayout(Comprar);
        Comprar.setLayout(ComprarLayout);
        ComprarLayout.setHorizontalGroup(
            ComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComprarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ComprarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComprarLayout.createSequentialGroup()
                        .addGroup(ComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jspCantidad)
                            .addComponent(jcbxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbxCodigos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE))
                    .addGroup(ComprarLayout.createSequentialGroup()
                        .addGroup(ComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnAgregarCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ComprarLayout.setVerticalGroup(
            ComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ComprarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(ComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComprarLayout.createSequentialGroup()
                        .addComponent(jcbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbxCodigos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jspCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(ComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComprarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(ComprarLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jbtnAgregarCarrito)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("tab1", Comprar);

        Carrito.setBackground(new java.awt.Color(255, 255, 255));

        jbtnPagar.setBackground(new java.awt.Color(104, 17, 130));
        jbtnPagar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnPagar.setForeground(new java.awt.Color(255, 239, 0));
        jbtnPagar.setText("PAGAR PRODUCTOS");
        jbtnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPagarActionPerformed(evt);
            }
        });

        jtblTablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "PRODUCTO", "CANTIDAD", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblTablaCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblTablaCarritoMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(jtblTablaCarrito);
        if (jtblTablaCarrito.getColumnModel().getColumnCount() > 0) {
            jtblTablaCarrito.getColumnModel().getColumn(0).setResizable(false);
            jtblTablaCarrito.getColumnModel().getColumn(0).setPreferredWidth(20);
            jtblTablaCarrito.getColumnModel().getColumn(1).setResizable(false);
            jtblTablaCarrito.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtblTablaCarrito.getColumnModel().getColumn(2).setResizable(false);
            jtblTablaCarrito.getColumnModel().getColumn(2).setPreferredWidth(20);
            jtblTablaCarrito.getColumnModel().getColumn(3).setResizable(false);
            jtblTablaCarrito.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("CARRITO DE COMPRAS");

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMACIÓN DE VENTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("SUBTOTAL");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("IGV");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("TOTAL");

        jlbSubtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jlbIgv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jlbTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(47, 47, 47)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jlbIgv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jlbSubtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jlbIgv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jlbTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setBackground(new java.awt.Color(104, 17, 130));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 239, 0));
        jButton3.setText("SELECCIONAR PRODUCTOS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jspNewCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jspNewCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MODIFICAR CANTIDAD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jspNewCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspNewCantidadStateChanged(evt);
            }
        });

        javax.swing.GroupLayout CarritoLayout = new javax.swing.GroupLayout(Carrito);
        Carrito.setLayout(CarritoLayout);
        CarritoLayout.setHorizontalGroup(
            CarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarritoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CarritoLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnPagar))
                    .addGroup(CarritoLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CarritoLayout.createSequentialGroup()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(CarritoLayout.createSequentialGroup()
                                .addComponent(jspNewCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        CarritoLayout.setVerticalGroup(
            CarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarritoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(CarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CarritoLayout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jspNewCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(CarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPagar)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", Carrito);

        Pagar.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jtxtApellidos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jtxtApellidos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jScrollPane2.setViewportView(jtxtApellidos);

        jtxtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jtxtNombre.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jScrollPane4.setViewportView(jtxtNombre);

        jtxtDireccion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jtxtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jScrollPane5.setViewportView(jtxtDireccion);

        jtxtDNI_Cliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DNI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jtxtDNI_Cliente.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jScrollPane6.setViewportView(jtxtDNI_Cliente);

        jtxtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jtxtEmail.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jScrollPane7.setViewportView(jtxtEmail);

        jtxtCelular.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Celular", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jtxtCelular.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jScrollPane8.setViewportView(jtxtCelular);

        jbtnCompletar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnCompletar.setForeground(new java.awt.Color(104, 17, 130));
        jbtnCompletar.setText("COMPLETAR DATOS");
        jbtnCompletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCompletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jbtnCompletar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnCompletar)
                        .addGap(68, 68, 68))))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MÉTODO DE PAGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jtxtNumTarjeta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Número de Tarjeta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jtxtNumTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jScrollPane9.setViewportView(jtxtNumTarjeta);

        jtxtFechaVencimiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha expiración", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jtxtFechaVencimiento.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jScrollPane10.setViewportView(jtxtFechaVencimiento);

        jtxtCCV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CCV", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jtxtCCV.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jScrollPane11.setViewportView(jtxtCCV);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN DE COMPRA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("SUBTOTAL");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("IGV");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("TOTAL");

        jlbResumenSubtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jlbResumenIGV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jlbResumenTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(79, 79, 79)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbResumenSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlbResumenTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addComponent(jlbResumenIGV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jlbResumenSubtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jlbResumenIGV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jlbResumenTotal))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jbtnProcesar.setBackground(new java.awt.Color(104, 17, 130));
        jbtnProcesar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnProcesar.setForeground(new java.awt.Color(255, 239, 0));
        jbtnProcesar.setText("PROCESAR COMPRA");
        jbtnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PagarLayout = new javax.swing.GroupLayout(Pagar);
        Pagar.setLayout(PagarLayout);
        PagarLayout.setHorizontalGroup(
            PagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PagarLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PagarLayout.createSequentialGroup()
                                .addComponent(jbtnProcesar)
                                .addGap(10, 10, 10))
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        PagarLayout.setVerticalGroup(
            PagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PagarLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnProcesar))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", Pagar);

        Historial.setBackground(new java.awt.Color(255, 255, 255));

        jtblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "FECHA", "MÉTODO DE PAGO", "IMPORTE"
            }
        ));
        jScrollPane3.setViewportView(jtblHistorial);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Historial de Compras");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("DNI:");

        jlbDNI_Historial.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("CLIENTE:");

        jlbDNIHis.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        javax.swing.GroupLayout HistorialLayout = new javax.swing.GroupLayout(Historial);
        Historial.setLayout(HistorialLayout);
        HistorialLayout.setHorizontalGroup(
            HistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistorialLayout.createSequentialGroup()
                .addGroup(HistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HistorialLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HistorialLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(HistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HistorialLayout.createSequentialGroup()
                                .addGroup(HistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(HistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbDNI_Historial, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbDNIHis, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        HistorialLayout.setVerticalGroup(
            HistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addGroup(HistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbDNI_Historial, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(HistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbDNIHis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", Historial);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 780, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void m1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m1MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_m1MouseClicked

    private void m2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m2MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_m2MouseClicked

    private void m3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m3MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_m3MouseClicked

    private void m4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m4MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);

        Ventas vt=new Ventas();
        vt.LlenarTabla();
    }//GEN-LAST:event_m4MouseClicked

    private void m1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m1MousePressed
        // TODO add your handling code here:
        
        p1.setBackground(clickedcolor);
        p2.setBackground(defaultcolor);
        p3.setBackground(defaultcolor);
        p4.setBackground(defaultcolor);
        m1.setForeground(white);
        
    }//GEN-LAST:event_m1MousePressed

    private void m1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m1MouseReleased
        // TODO add your handling code here:
        p1.setBackground(defaultcolor);
        m1.setForeground(purple);
        
    }//GEN-LAST:event_m1MouseReleased

    private void m2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m2MousePressed
        // TODO add your handling code here:
        p1.setBackground(defaultcolor);
        p2.setBackground(clickedcolor);
        p3.setBackground(defaultcolor);
        p4.setBackground(defaultcolor);
        m2.setForeground(white);
        
    }//GEN-LAST:event_m2MousePressed

    private void m2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m2MouseReleased
        // TODO add your handling code here:
        p2.setBackground(defaultcolor);
        m2.setForeground(purple);
        
    }//GEN-LAST:event_m2MouseReleased

    private void m3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m3MousePressed
        // TODO add your handling code here:
        p1.setBackground(defaultcolor);
        p2.setBackground(defaultcolor);
        p3.setBackground(clickedcolor);
        p4.setBackground(defaultcolor);
        m3.setForeground(white);
    }//GEN-LAST:event_m3MousePressed

    private void m3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m3MouseReleased
        // TODO add your handling code here:
        p3.setBackground(defaultcolor);
        m3.setForeground(purple);
    }//GEN-LAST:event_m3MouseReleased

    private void m4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m4MousePressed
        // TODO add your handling code here:
        p1.setBackground(defaultcolor);
        p2.setBackground(defaultcolor);
        p3.setBackground(defaultcolor);
        p4.setBackground(clickedcolor);
        m4.setForeground(white);
    }//GEN-LAST:event_m4MousePressed

    private void m4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m4MouseReleased
        // TODO add your handling code here:
        p4.setBackground(defaultcolor);
        m4.setForeground(purple);
    }//GEN-LAST:event_m4MouseReleased

    private void jcbxCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbxCategoriaItemStateChanged
        // TODO add your handling code here:
        
        //Cargamos la información de los productos en la TABLA PRODUCTOS.
        
        if(evt.getStateChange()==ItemEvent.SELECTED){
            
            Categorias ctg=(Categorias)jcbxCategoria.getSelectedItem();
            Codigos code=new Codigos();
            DefaultComboBoxModel modelCode=new DefaultComboBoxModel(code.mostrarCodigos(ctg.getCategoria()));
            jcbxCodigos.setModel(modelCode);
            try{
                DefaultTableModel modelo= new DefaultTableModel();
                jtblProductos.setModel(modelo);
                
                PreparedStatement ps=null;
                ResultSet rs=null;
                Conexion cx=new Conexion();
                Connection con=cx.getConexion();
                
                String sql="Select Codigo, Producto, Descripcion, Precio from PRODUCTO WHERE Categoria='"+ctg.getCategoria()+"'";
                System.out.println(sql);
                ps=con.prepareStatement(sql);
                rs=ps.executeQuery();
                
                ResultSetMetaData rsMd=rs.getMetaData();
                int cantidadColumnas=rsMd.getColumnCount();
                
                modelo.addColumn("Código");
                modelo.addColumn("Producto");
                modelo.addColumn("Descripción");
                modelo.addColumn("Precio");
                
                int [] anchos={20,175,175,20};
                
                for(int x=0; x<cantidadColumnas;x++){
                    jtblProductos.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
                    
                }
                
                while(rs.next()){
                    Object[]filas=new Object[cantidadColumnas];
                    
                    for(int i=0; i<cantidadColumnas;i++){
                        filas[i]=rs.getObject(i+1);
                    }
                    modelo.addRow(filas);
                }
            }catch(SQLException ex){
                System.err.println(ex.toString());
            }
        }
    }//GEN-LAST:event_jcbxCategoriaItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarCarritoActionPerformed
        Productos Carrito=new Productos();
        
        Carrito.setCodigo(jcbxCodigos.getSelectedItem().toString());
        Carrito.setProducto(jlbProducto.getText());
        Carrito.setPrecio(precio);
        Carrito.setCantidad(cantidad);
        
        importe=Math.round(precio*cantidad);
        
        Carrito.setImporte(importe);
        
        jspCantidad.setValue(1);
        jcbxCategoria.setSelectedIndex(0);
        jcbxCodigos.setSelectedIndex(0);
        
        ListaVentas.add(Carrito); //Agregamos los productos seleccionados a la tabla carrito
        ActualizarTabla(); //Actualizamos la tabla
        BorrarVenta();
        
        
    }//GEN-LAST:event_jbtnAgregarCarritoActionPerformed
    public void BorrarVenta(){
        precio=0;
        cantidad=0;
  
    }
    public void ActualizarTabla(){
        
        //Creamos la tabla CARRITO DE COMPRAS
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Producto");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Importe");
        
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        double subTotal=0;
        
        
        //Mostramos los atributos de la tabla Carrito y se calculan los
        //diferentes importes.
        for(Productos c:ListaVentas){ 
            Object x[]=new  Object[5];
            x[0]=c.getCodigo();
            x[1]=c.getProducto();
            x[2]=c.getPrecio();
            x[3]=c.getCantidad();
            x[4]=c.getImporte();
            subTotal+=c.getImporte();
            
            jtblTablaCarrito.getColumnModel().getColumn(0).setPreferredWidth(20);
            modelo.addRow(x);
        }
        
        double igv=Math.round(subTotal*0.18);
        
        double total=subTotal+igv;
        
        jlbSubtotal.setText(aMoneda(subTotal));
        jlbIgv.setText(aMoneda(igv));
        jlbTotal.setText(aMoneda(total));
        jtblTablaCarrito.setModel(modelo);
        
        jlbResumenSubtotal.setText(aMoneda(subTotal));
        jlbResumenIGV.setText(aMoneda(igv));
        jlbResumenTotal.setText(aMoneda(total));
    }
    private void jbtnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPagarActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
  
    }//GEN-LAST:event_jbtnPagarActionPerformed

    private void jbtnCompletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCompletarActionPerformed
        //BOTÓN completar datos
        
        String DNI=this.jtxtDNI_Cliente.getText();
        PreparedStatement ps=null;
        ResultSet rs=null;
        Conexion cx=new Conexion();
        Connection con=cx.getConexion();
        String sql="SELECT DNI, Nombre, Apellido, Celular, Direccion, Email FROM CLIENTE where DNI='"+DNI+"'";
        try{
            //String sql="SELECT DNI, Nombre, Apellido, Celular, Direccion, Email FROM CLIENTE where DNI='"+DNI+"'";
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            if(rs.next()){
                   //Si existe el Email
                    String nom=rs.getString("Nombre");
                    jtxtNombre.setText(nom);
                    String ap=rs.getString("Apellido");
                    jtxtApellidos.setText(ap);
                    String cel=rs.getString("Celular");
                    jtxtCelular.setText(cel);
                    String dc=rs.getString("Direccion");
                    jtxtDireccion.setText(dc);
                    String em=rs.getString("Email");
                    jtxtEmail.setText(em);
                   }else{
                       JOptionPane.showMessageDialog(null, "USUARIO NO REGISTRADO, INGRESE LOS DATOS MANUALMENTE");
                   }
        }catch(SQLException ex){
            System.err.println(ex.toString());
        } 
    }//GEN-LAST:event_jbtnCompletarActionPerformed

    private void jcbxCodigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxCodigosActionPerformed
        // TODO add your handling code here:
        CalcularPrecio();
    }//GEN-LAST:event_jcbxCodigosActionPerformed

    private void jcbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxCategoriaActionPerformed

    private void jspCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspCantidadStateChanged
        // TODO add your handling code here:
        CalcularPrecio();
    }//GEN-LAST:event_jspCantidadStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // BOTÓN ver mi carrito
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // BOTÓN agregar productos
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbtnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProcesarActionPerformed
        // TODO add your handling code here:
        
        String NumTarjeta=this.jtxtNumTarjeta.getText().trim();
        String FechaVencimiento=this.jtxtFechaVencimiento.getText().trim();
        String CCV=this.jtxtCCV.getText().trim();
        
        MetodoPago mp=new MetodoPago(NumTarjeta,FechaVencimiento, CCV );
        
        mp.ValidarTarjeta();
        
        
        
        
      
    }//GEN-LAST:event_jbtnProcesarActionPerformed
    
       
        
    private void jtblTablaCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblTablaCarritoMouseClicked
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_jtblTablaCarritoMouseClicked

    private void jspNewCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspNewCantidadStateChanged
        // TODO add your handling code here:
        int filaSeleccionada = this.jtblTablaCarrito.getSelectedRow();
                int columnaCantidad = 3;
                if (filaSeleccionada != -1) {
                    Object nuevoValor = jspNewCantidad.getValue();
                    int cantidad1= (int) nuevoValor;
                    double precio1= (double)jtblTablaCarrito.getValueAt(filaSeleccionada, 2);
                    double importe1=Math.round(precio1*(cantidad1));
                    
                    
                    jtblTablaCarrito.setValueAt(nuevoValor, filaSeleccionada, columnaCantidad);
                    
                    jtblTablaCarrito.setValueAt(importe1,filaSeleccionada, 4 );
                }
        double subTotalNuevo=0.0;
        double IGVnuevo=0.0;
        double importeNuevo=0.0;
        for (int fila = 0; fila < jtblTablaCarrito.getRowCount(); fila++) {
         
        Object importeObjeto = jtblTablaCarrito.getValueAt(fila, 4);
        if (importeObjeto instanceof Double) {
            double importe = (double) importeObjeto;
            subTotalNuevo += importe;
            IGVnuevo=Math.round(subTotalNuevo * 0.18 * 100.0) / 100.0;
            importeNuevo=subTotalNuevo+IGVnuevo;
            
            this.jlbSubtotal.setText(aMoneda(subTotalNuevo));
            this.jlbIgv.setText(aMoneda(IGVnuevo));
            this.jlbTotal.setText(aMoneda(importeNuevo));
            
            this.jlbResumenSubtotal.setText(aMoneda(subTotalNuevo));
            this.jlbResumenIGV.setText(aMoneda(IGVnuevo));
            this.jlbResumenTotal.setText(aMoneda(importeNuevo));
            
            
            
    }
}
        
    }//GEN-LAST:event_jspNewCantidadStateChanged
    
    public void CalcularPrecio(){
        
        String Codigo=this.jcbxCodigos.getSelectedItem().toString();
        cantidad=Integer.parseInt(this.jspCantidad.getValue().toString());
        PreparedStatement ps=null;
        ResultSet rs=null;
        Conexion cx=new Conexion();
        Connection con=cx.getConexion();
        
        try{
            String sql="SELECT Precio, Producto FROM PRODUCTO where Codigo='"+Codigo+"'";
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            rs.next();
            
            String producto=rs.getString("Producto");
            jlbProducto.setText(producto);
            precio=Double.parseDouble(rs.getString("Precio"));
            jblPrecio.setText(aMoneda(precio));
            jblImporte.setText(aMoneda(Math.round(precio * cantidad * 100.0) / 100.0));
            
        }catch(SQLException ex){
            System.err.println(ex.toString());
        }
    }
    
    public String aMoneda(double precio){
        return "S/. "+precio;
    }
    
    public void ActualizarTablaCarrito(){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLat Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Carrito;
    private javax.swing.JPanel Comprar;
    private javax.swing.JPanel Historial;
    private javax.swing.JPanel Pagar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jblImporte;
    private javax.swing.JLabel jblPrecio;
    private javax.swing.JButton jbtnAgregarCarrito;
    private javax.swing.JButton jbtnCompletar;
    private javax.swing.JButton jbtnPagar;
    private javax.swing.JButton jbtnProcesar;
    private javax.swing.JComboBox<String> jcbxCategoria;
    private javax.swing.JComboBox<String> jcbxCodigos;
    public static javax.swing.JLabel jlbDNIHis;
    public javax.swing.JLabel jlbDNI_Historial;
    private javax.swing.JLabel jlbIgv;
    private javax.swing.JLabel jlbProducto;
    private javax.swing.JLabel jlbResumenIGV;
    private javax.swing.JLabel jlbResumenSubtotal;
    public static javax.swing.JLabel jlbResumenTotal;
    private javax.swing.JLabel jlbSubtotal;
    private javax.swing.JLabel jlbTotal;
    private javax.swing.JSpinner jspCantidad;
    public javax.swing.JSpinner jspNewCantidad;
    public static javax.swing.JTable jtblHistorial;
    private javax.swing.JTable jtblProductos;
    private javax.swing.JTable jtblTablaCarrito;
    private javax.swing.JTextPane jtxtApellidos;
    public static javax.swing.JTextPane jtxtCCV;
    private javax.swing.JTextPane jtxtCelular;
    public static javax.swing.JTextPane jtxtDNI_Cliente;
    private javax.swing.JTextPane jtxtDireccion;
    private javax.swing.JTextPane jtxtEmail;
    public static javax.swing.JTextPane jtxtFechaVencimiento;
    private javax.swing.JTextPane jtxtNombre;
    public static javax.swing.JTextPane jtxtNumTarjeta;
    private javax.swing.JLabel m1;
    private javax.swing.JLabel m2;
    private javax.swing.JLabel m3;
    private javax.swing.JLabel m4;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    // End of variables declaration//GEN-END:variables
}
